s = input()
print(map(str.isalnum,list(s)))
if any(map(str.isalnum,list(s))):print("True")
else:print("False")
if any(map(str.isalpha,list(s))):print("True")
else:print("False")
if any(map(str.isdigit,list(s))):print("True")
else:print("False")
if any(map(str.islower,list(s))):print("True")
else:print("False")
if any(map(str.isupper,list(s))):print("True")
else:print("False") 